FROM python:3

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /code

ADD requirements.txt /code/

RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

ADD . /code/

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]