version: '3'

services:
  db:
    image: postgres
    env_file: .env_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/postgres_log
  redis:
    image: redis:5
    ports: 
      - 6379:6379
  web:
    build:  
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
      - "8000"
    env_file: .env 
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/usr/src/app/staticfiles
    ports: 
      - 1337:80
    depends_on:
      - web
volumes: 
    postgres_data:
    postgres_log:
    static_volume:
    